export const REACT_REDUX_SAGA_BOILERPLATE = "REACT_REDUX_SAGA_BOILERPLATE";
export const ON_ADD_CLICK = "ON_ADD_CLICK";
export const SAGA_RUNNING_CHECK = "SAGA_RUNNING_CHECK";
export const LOGOUT_FROM_THE_PAGE = "LOGOUT_FROM_THE_PAGE";
